import Header from "@/components/layout/Header";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>


      </body>

    </html>
  );
}
